# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DDDownload' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DDDownload
  pod 'Masonry'
  pod 'Reachability'
  pod 'SDWebImage', '~> 4.0'


  target 'DDDownloadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DDDownloadUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
