# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DDDownload' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DDDownload
  pod 'Masonry'
  pod 'Reachability'
  pod 'SDWebImage', '~> 4.0'
  pod 'YYCache'
  pod 'YYModel'
  target 'DDDownloadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DDDownloadUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
